# Generated by Django 4.2.2 on 2023-07-03 10:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_todomodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todomodel",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
