# Generated by Django 4.2.2 on 2023-06-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="user_img",
            field=models.ImageField(default="main/img/user.png", upload_to="user/"),
        ),
    ]
